/* ============================================================
 * data.js — CPB試染工具：查表資料 / 雙語字典
 * 這個檔案只放「資料」，不放邏輯。修改鹼劑波美度對照表、水玻璃/非水玻璃
 * 鹼劑用量表、雙語字串時改這裡；改計算邏輯或畫面互動去改 app.js。
 * 載入順序要排在 app.js 之前（app.js 會直接使用這裡定義的常數）。
 * ============================================================ */

/* ---- 中英文對照 ---- */
        const translations = {
            zh: {
                title: 'CPB試染工具',
                subtitle: '冷壓染染色工藝',
                shareButton: '分享',
                saveImageInstruction: '長按下方圖片,選擇「儲存圖片」即可儲存到手機相簿',
                closeButton: '關閉',
                cancelButton: '取消',
                loadRecipe: '載入已儲存配方',
                loadRecipeLabel: '載入配方',
                saveRecipeLabel: '儲存配方',
                selectRecipe: '-- 選擇已儲存的配方 --',
                delete: '刪除',
                orderInfo: '訂單資訊',
                customer: '客戶',
                customerPlaceholder: '客戶名稱',
                colorOrder: '顏色/訂單號',
                colorOrderPlaceholder: '顏色名稱或訂單號',
                colorOrderLabel: '顏色/訂單:',
                fabricType: '布料類型',
                fabricTypePlaceholder: '例如: 100% 棉',
                fabricInputPrompt: '請先在上方填寫「總布量」與「軋吸率」,才會顯示後續的配方與計算內容',
                dyeInputPrompt: '請先在上方「染料配方」填寫染料用量,才會顯示鹼劑建議配方',
                batchTime: '堆置時間 (小時)',
                processTime: '製程時間',
                runningSpeed: '車速 (m/min)',
                estimatedRunTime: '預估軋染時間: ',
                fabricAutoCalcHint: '總布量、布重、布長三項填其中任兩項,第三項會自動算出來;三項都填的話,以最近修改的兩項為準',
                fabricInfo: '布料資訊',
                totalFabric: '總布量 (kg)',
                fabricWeight: '布重 (g/m)',
                fabricLength: '布長 (m)',
                totalFabricCalc: '總布量: ',
                pickup: '軋吸率 (%)',
                solutionPrep: '溶液配製',
                theoreticalSolution: '最低需求溶液量: ',
                dosingRatio: '配比 4:1 → ',
                dye: '染料: ',
                alkali: '鹼劑: ',
                dyeSolutionPrepare: '配製染料溶液 (ltr)',
                alkaliSolutionPrepare: '配製鹼液 (ltr)',
                vsTheoretical: '較最低需求: ',
                dyeRecipe: '染料配方',
                prepareInDye: '配製染料溶液: ',
                item: '項目',
                recipeGl: '配方 (g/l)',
                bulkG: '用量 (g)',
                total: '總計:',
                auxiliaries: '助劑',
                dyePlaceholder: '染料',
                auxPlaceholder: '助劑',
                addDyeRow: '＋ 新增染料',
                addAuxRow: '＋ 新增助劑',
                deleteLastDyeRow: '－ 刪除',
                deleteLastAuxRow: '－ 刪除',
                minRowWarning: '至少要保留一列',
                dyeDefault1: '黃色',
                dyeDefault2: '紅色',
                dyeDefault3: '藍色',
                auxDefault1: '滲透劑',
                alkaliSystem: '鹼劑配方',
                alkaliMethodSection: '鹼劑方法設定',
                alkaliMethod: '鹼劑方法',
                methodA: 'A. 非水玻璃法',
                methodB: 'B. 水玻璃法',
                methodC: 'C. 改性水玻璃法',
                methodD: 'D. 非水玻璃法(熱帶地區)',
                prepareInAlkali: '配製鹼液: ',
                naohType: '液鹼類型',
                naohFlakes: '片鹼 (100% w/w)',
                custom: '自定義',
                baume: '波美度 (°Bé)',
                basedOnDye: '基於染料: ',
                silicateConc: '水玻璃濃度',
                naohConc: '液鹼濃度',
                suggested: '建議配方',
                actual: '實際配方',
                naohTable: '液鹼濃度表',
                alkaliBasis: '鹼劑推薦依據',
                specWeight: '比重 (ρ)',
                naohContent: '液鹼含量 (g/l)',
                naohPercent: '液鹼 % (w/w)',
                workOrder: 'CPB生產工作單',
                download: '下載',
                downloadImage: '下載圖片',
                saveAsPdf: '另存為 PDF',
                date: '日期:',
                qty: '總布量:',
                fabricLabel: '布料:',
                alkaliLabel: '鹼劑:',
                batchTimeLabel: '堆置時間:',
                runningSpeedLabel: '車速:',
                estimatedRunTimeLabel: '預估軋吸:',
                pickupLabel: '軋吸率:',
                dyeingCompletionSection: '染色完成記錄',
                paddingEndTime: '軋吸結束時間',
                nowButton: '現在',
                suggestedWashTime: '建議水洗時間: ',
                paddingEndTimePrompt: '請填寫「軋吸結束時間」,即可算出建議水洗時間',
                woPaddingEndTimeLabel: '軋吸結束:',
                woSuggestedWashTimeLabel: '建議水洗:',
                navOrder: '訂單布料',
                tabFormSettings: '配方設定',
                tabPretreatment: '前處理',
                tabWashing: '水洗',
                tabWorkCard: '工卡',
                cardTabPrompt: '請先在「配方設定」分頁填寫「總布量」與「軋吸率」,才會顯示工卡內容',
                dyeResultSection: '染色結果記錄',
                takePhoto: '拍照',
                uploadPhoto: '上傳照片',
                dyeResultLabel: '染色結果',
                dyeResultPlaceholder: '記錄染色結果、色差、備註...',
                tabDyeResult: '染色結果',
                photoCaptionPlaceholder: '這張照片的說明...',
                navAlkaliMethod: '鹼劑設定',
                navDyeRecipe: '染料/鹼劑配方',
                navWorkOrder: '工作單',
                requiredSol: '最低需求量',
                prepareDye: '配製染料溶液',
                prepareAlkali: '配製鹼液',
                dyeSolRecipe: '染料溶液配方',
                prepare: '配製:',
                alkaliSolRecipe: '鹼液配方',
                quantity: '用量 (g)',
                saveRecipe: '儲存當前配方',
                saveRecipePlaceholder: '輸入配方名稱 (例如: 紅色-棉布-客戶A)',
                saveButton: '儲存',
                clearDraft: '清除目前內容',
                pretreatmentSection: '前處理設定',
                pretreatmentMethod: '前處理方式',
                pretreatmentNone: '未使用前處理',
                pretreatmentContinuous: '連續式 (Continuous)',
                pretreatmentColdBleach: '冷漂 (Cold Bleach)',
                pretreatmentJet: '溢流染機 (Jet)',
                pretreatmentDemin: '第一段:脫礦 (Demineralization)',
                pretreatmentBleach: '第二段:漂白 (Bleaching)',
                temperature: '溫度 (°C)',
                processTime: '處理時間 (分鐘)',
                chemicalName: '藥劑名稱',
                chemicalNamePlaceholder: '藥劑',
                dosageGL: '用量 (g/l)',
                addRowGeneric: '＋ 新增',
                removeRowGeneric: '－ 刪除',
                stage: '段',
                washingSection: '水洗設定',
                washingMethod: '水洗方式',
                washingNone: '未使用水洗設定',
                washingContinuous: '連續式 (Continuous)',
                washingJet: '溢流染機 (Jet)',
                runningSpeedWashing: '車速 (m/min)',
                waterFlow: '流量 (L/min)',
                woPretreatmentLabel: '前處理:',
                woWashingLabel: '水洗:',
            },
            en: {
                title: 'CPB Trial Tool',
                subtitle: 'Cold Pad Batch Process',
                shareButton: 'Share',
                saveImageInstruction: 'Press and hold the image below, then select "Save Image" to save it to your Photos',
                closeButton: 'Close',
                cancelButton: 'Cancel',
                loadRecipe: 'Load Saved Recipe',
                loadRecipeLabel: 'Load Recipe',
                saveRecipeLabel: 'Save Recipe',
                selectRecipe: '-- Select a saved recipe --',
                delete: 'Delete',
                orderInfo: 'Order Information',
                customer: 'Customer',
                customerPlaceholder: 'Customer Name',
                colorOrder: 'Color/Order',
                colorOrderPlaceholder: 'Color Name or Order No.',
                colorOrderLabel: 'Color/Order:',
                fabricType: 'Fabric Type',
                fabricTypePlaceholder: 'e.g. 100% Cotton',
                fabricInputPrompt: 'Please fill in "Total Fabric Quantity" and "Pickup" above first, to see the recipe and calculation content below',
                dyeInputPrompt: 'Please fill in the dye amount in "Dye Recipe" above first, to see the alkali recommendation',
                batchTime: 'Batch Time (hrs)',
                processTime: 'Process Time',
                runningSpeed: 'Running Speed (m/min)',
                estimatedRunTime: 'Estimated Padding Time: ',
                fabricAutoCalcHint: 'Fill in any two — the third is calculated automatically; if all three are filled, the two most recently edited take priority',
                fabricInfo: 'Fabric Information',
                totalFabric: 'Fabric Quantity (kg)',
                fabricWeight: 'Fabric Weight (g/m)',
                fabricLength: 'Fabric Length (m)',
                totalFabricCalc: 'Fabric: ',
                pickup: 'Pickup (%)',
                solutionPrep: 'Solution Preparation',
                theoreticalSolution: 'Minimum Required Solution: ',
                dosingRatio: 'Dosing Ratio 4:1 → ',
                dye: 'Dye: ',
                alkali: 'Alkali: ',
                dyeSolutionPrepare: 'Dye Solution to Prepare (ltr)',
                alkaliSolutionPrepare: 'Alkali Solution to Prepare (ltr)',
                vsTheoretical: 'vs Minimum Required: ',
                dyeRecipe: 'Dye Recipe',
                prepareInDye: 'Prepare in Dye Solution: ',
                item: 'Item',
                recipeGl: 'Recipe (g/l)',
                bulkG: 'Quantity (g)',
                total: 'Total:',
                auxiliaries: 'Auxiliaries',
                dyePlaceholder: 'Dye',
                auxPlaceholder: 'Auxiliary',
                addDyeRow: '+ Add Dye',
                addAuxRow: '+ Add Auxiliary',
                deleteLastDyeRow: '- Remove',
                deleteLastAuxRow: '- Remove',
                minRowWarning: 'At least one row is required',
                dyeDefault1: 'Yellow',
                dyeDefault2: 'Red',
                dyeDefault3: 'Blue',
                auxDefault1: 'Wetting Agent',
                alkaliSystem: 'Alkali Recipe',
                alkaliMethodSection: 'Alkali Method Setup',
                alkaliMethod: 'Alkali Method',
                methodA: 'A. Silicate-Free Method',
                methodB: 'B. Sodium Silicate Method',
                methodC: 'C. Modified Sodium Silicate Method',
                methodD: 'D. Silicate-Free Method (Tropical Region)',
                prepareInAlkali: 'Prepare in Alkali Solution: ',
                naohType: 'NaOH Type',
                naohFlakes: 'NaOH Flakes (100% w/w)',
                custom: 'Custom',
                baume: 'Baumé (°Bé)',
                basedOnDye: 'Based on Dye: ',
                silicateConc: 'Sodium Silicate Concentration',
                naohConc: 'NaOH Concentration',
                suggested: 'Suggested',
                actual: 'Actual',
                naohTable: 'NaOH Concentration Table',
                alkaliBasis: 'Alkali Recommendation Basis',
                specWeight: 'Specific Weight (ρ)',
                naohContent: 'NaOH Content (g/l)',
                naohPercent: 'NaOH % (w/w)',
                workOrder: 'CPB Production Sheet',
                download: 'Download',
                downloadImage: 'Download Image',
                saveAsPdf: 'Save as PDF',
                date: 'Date:',
                qty: 'Fabric Quantity:',
                fabricLabel: 'Fabric:',
                alkaliLabel: 'Alkali:',
                batchTimeLabel: 'Batch Time:',
                runningSpeedLabel: 'Speed:',
                estimatedRunTimeLabel: 'Padding Time:',
                pickupLabel: 'Pickup:',
                dyeingCompletionSection: 'Dyeing Completion Record',
                paddingEndTime: 'Padding End Time',
                nowButton: 'Now',
                suggestedWashTime: 'Suggested Washing Time: ',
                paddingEndTimePrompt: 'Enter the padding end time to calculate the suggested washing time',
                woPaddingEndTimeLabel: 'Padding End:',
                woSuggestedWashTimeLabel: 'Suggested Wash:',
                navOrder: 'Order',
                tabFormSettings: 'Recipe',
                tabPretreatment: 'Prep',
                tabWashing: 'Wash',
                tabWorkCard: 'Card',
                cardTabPrompt: 'Please fill in "Total Fabric" and "Pickup %" on the Recipe Setup tab to see the work card',
                dyeResultSection: 'Dyeing Result Record',
                takePhoto: 'Take Photo',
                uploadPhoto: 'Upload Photo',
                dyeResultLabel: 'Dyeing Result',
                dyeResultPlaceholder: 'Notes on dyeing result, shade variance, etc...',
                tabDyeResult: 'Result',
                photoCaptionPlaceholder: 'Caption for this photo...',
                navAlkaliMethod: 'Alkali',
                navDyeRecipe: 'Recipe',
                navWorkOrder: 'Work Order',
                requiredSol: 'Min. Required Sol.',
                prepareDye: 'Prepare Dye Sol.',
                prepareAlkali: 'Prepare Alkali Sol.',
                dyeSolRecipe: 'Dye Solution Recipe',
                prepare: 'Prepare:',
                alkaliSolRecipe: 'Alkali Solution Recipe',
                quantity: 'Quantity (g)',
                saveRecipe: 'Save Current Recipe',
                saveRecipePlaceholder: 'Enter recipe name (e.g., Red-Cotton-CustomerA)',
                saveButton: 'Save',
                clearDraft: 'Clear current content',
                pretreatmentSection: 'Pretreatment Settings',
                pretreatmentMethod: 'Pretreatment Method',
                pretreatmentNone: 'Not Used',
                pretreatmentContinuous: 'Continuous',
                pretreatmentColdBleach: 'Cold Bleach',
                pretreatmentJet: 'Jet Machine',
                pretreatmentDemin: 'Stage 1: Demineralization',
                pretreatmentBleach: 'Stage 2: Bleaching',
                temperature: 'Temperature (°C)',
                processTime: 'Process Time (min)',
                chemicalName: 'Chemical Name',
                chemicalNamePlaceholder: 'Chemical',
                dosageGL: 'Dosage (g/l)',
                addRowGeneric: '+ Add',
                removeRowGeneric: '- Remove',
                stage: 'Stage',
                washingSection: 'Washing Settings',
                washingMethod: 'Washing Method',
                washingNone: 'Not Used',
                washingContinuous: 'Continuous',
                washingJet: 'Jet Machine',
                runningSpeedWashing: 'Running Speed (m/min)',
                waterFlow: 'Water Flow (L/min)',
                woPretreatmentLabel: 'Pretreatment:',
                woWashingLabel: 'Washing:',
            }
        };

/* ---- 鹼劑波美度對照表 ---- */
        const baumeTable = {
            1: { rho: 1.007, gl: 6.0, percent: 0.59 },
            2: { rho: 1.014, gl: 12.0, percent: 1.18 },
            3: { rho: 1.022, gl: 18.9, percent: 1.85 },
            4: { rho: 1.029, gl: 25.7, percent: 2.50 },
            5: { rho: 1.036, gl: 32.6, percent: 3.15 },
            6: { rho: 1.045, gl: 39.6, percent: 3.79 },
            7: { rho: 1.052, gl: 47.3, percent: 4.50 },
            8: { rho: 1.060, gl: 55.0, percent: 5.20 },
            9: { rho: 1.067, gl: 62.5, percent: 5.86 },
            10: { rho: 1.075, gl: 70.7, percent: 6.58 },
            11: { rho: 1.083, gl: 79.1, percent: 7.30 },
            12: { rho: 1.091, gl: 88.0, percent: 8.07 },
            13: { rho: 1.100, gl: 96.6, percent: 8.78 },
            14: { rho: 1.108, gl: 105.3, percent: 9.50 },
            15: { rho: 1.116, gl: 114.9, percent: 10.30 },
            16: { rho: 1.125, gl: 124.4, percent: 11.06 },
            17: { rho: 1.134, gl: 134.0, percent: 11.84 },
            18: { rho: 1.142, gl: 145.0, percent: 12.60 },
            19: { rho: 1.152, gl: 155.5, percent: 13.50 },
            20: { rho: 1.161, gl: 166.7, percent: 14.35 },
            21: { rho: 1.171, gl: 177.4, percent: 15.15 },
            22: { rho: 1.180, gl: 188.8, percent: 16.00 },
            23: { rho: 1.190, gl: 201.2, percent: 16.91 },
            24: { rho: 1.200, gl: 213.7, percent: 17.81 },
            25: { rho: 1.210, gl: 226.4, percent: 18.71 },
            26: { rho: 1.220, gl: 239.7, percent: 19.65 },
            27: { rho: 1.231, gl: 253.6, percent: 20.60 },
            28: { rho: 1.241, gl: 267.4, percent: 21.55 },
            29: { rho: 1.252, gl: 281.7, percent: 22.50 },
            30: { rho: 1.263, gl: 296.8, percent: 23.50 },
            31: { rho: 1.274, gl: 311.9, percent: 24.48 },
            32: { rho: 1.285, gl: 327.7, percent: 25.50 },
            33: { rho: 1.297, gl: 344.7, percent: 26.58 },
            34: { rho: 1.308, gl: 361.7, percent: 27.65 },
            35: { rho: 1.320, gl: 380.6, percent: 28.83 },
            36: { rho: 1.332, gl: 399.6, percent: 30.00 },
            37: { rho: 1.345, gl: 419.6, percent: 31.20 },
            38: { rho: 1.357, gl: 441.0, percent: 32.50 },
            39: { rho: 1.370, gl: 462.1, percent: 33.73 },
            40: { rho: 1.383, gl: 484.1, percent: 35.00 },
            41: { rho: 1.397, gl: 507.9, percent: 36.36 },
            42: { rho: 1.410, gl: 530.9, percent: 37.65 },
            43: { rho: 1.424, gl: 556.2, percent: 39.06 },
            44: { rho: 1.438, gl: 582.0, percent: 40.47 },
            45: { rho: 1.453, gl: 610.6, percent: 42.02 },
            46: { rho: 1.468, gl: 639.8, percent: 43.58 },
            47: { rho: 1.483, gl: 669.7, percent: 45.16 },
            48: { rho: 1.498, gl: 700.0, percent: 46.73 },
            49: { rho: 1.514, gl: 732.9, percent: 48.41 },
            50: { rho: 1.530, gl: 766.5, percent: 50.10 }
        };

/* ---- 熱帶地區液鹼用量表 ---- */
        const tropicalRegionNaOH = {
            ranges: [
                { min: -Infinity, max: 10, cc: 2.5 },
                { min: 10, max: 20, cc: 3.0 },
                { min: 20, max: 40, cc: 4.5 },
                { min: 40, max: 60, cc: 6.5 },
                { min: 60, max: 80, cc: 8.5 },
                { min: 80, max: 100, cc: 10.5 },
                { min: 100, max: Infinity, cc: 12.0 }
            ]
        };

/* ---- 水玻璃法鹼劑用量表 B/C ---- */
        const sodiumSilicateDataB = {
            '37-40': { gl: 130, naoh: { 20: 23.5, 30: 28.5, 40: 28.5, 50: 33.5, 60: 33.5, 70: 38.5 } },
            '40-42': { gl: 110, naoh: { 20: 23.5, 30: 28.5, 40: 28.5, 50: 33.5, 60: 33.5, 70: 38.5 } },
            '48-50': { gl: 100, naoh: { 20: 15, 30: 20, 40: 20, 50: 25, 60: 25, 70: 30 } },
            '58-60': { gl: 90, naoh: { 20: 6, 30: 11, 40: 11, 50: 16, 60: 16, 70: 21 } }
        };

        const sodiumSilicateDataC = {
            '37-40': { gl: 65, naoh: { 10: 7, 20: 12, 30: 12, 40: 17, 50: 17, 60: 22 } },
            '40-42': { gl: 55, naoh: { 10: 7, 20: 12, 30: 12, 40: 17, 50: 17, 60: 22 } },
            '48-50': { gl: 50, naoh: { 10: 5, 20: 10, 30: 10, 40: 15, 50: 15, 60: 20 } },
            '58-60': { gl: 45, naoh: { 10: 3, 20: 7, 30: 7, 40: 11, 50: 11, 60: 16 } }
        };

/* ---- 燒鹼濃度基礎資料 ---- */
        const naohConcData = {
            '38': { specWeight: 1.357, contentGl: 441.0 },
            '50': { specWeight: 1.530, contentGl: 766.5 },
            'flakes': { specWeight: 1.0, contentGl: 1000.0 }
        };

/* ---- 非水玻璃法(常規)鹼劑用量表 A ---- */
        const silicateFreeRegularTableA = [
            { max: 10,        sodaAsh: 20, naoh50CcPerL: 4.0,  naoh50GPerL: 6.0,  naohFlakesGPerL: 3.00 },
            { max: 20,        sodaAsh: 20, naoh50CcPerL: 5.0,  naoh50GPerL: 7.5,  naohFlakesGPerL: 3.75 },
            { max: 40,        sodaAsh: 20, naoh50CcPerL: 7.0,  naoh50GPerL: 10.5, naohFlakesGPerL: 5.25 },
            { max: 60,        sodaAsh: 20, naoh50CcPerL: 10.0, naoh50GPerL: 15.0, naohFlakesGPerL: 7.50 },
            { max: 80,        sodaAsh: 20, naoh50CcPerL: 12.5, naoh50GPerL: 19.0, naohFlakesGPerL: 9.50 },
            { max: 100,       sodaAsh: 20, naoh50CcPerL: 15.0, naoh50GPerL: 23.0, naohFlakesGPerL: 11.50 },
            { max: Infinity,  sodaAsh: 20, naoh50CcPerL: 16.5, naoh50GPerL: 25.0, naohFlakesGPerL: 12.50 }
        ];
